language: python
python:
  - "3.6"
before_install:
  # Create the virtual env and lint the codebase
  - make lint VENV_EXTRA_ARGS="--system-site-packages"
  # Install the codecov reporting utility
  - pip install codecov
script:
  - make test
after_success:
  # Report test coverage to codecov.io
  - codecov
notifications:
  email: false
